version: '3.7'
services:

  db:
    container_name: 'db'
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env-docker
    ports:
      - '5433:5432'

  redis:
    container_name: 'redis'
    image: redis:7
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env-docker
    ports:
      - '6379:6379'

  app:
    container_name: 'app'
    build:
      context: ../../
    command: ['/app/docker/app.sh']
    restart: always
    volumes:
      - static:/app/source/static/
      - media:/app/source/media/
    depends_on:
      - db
      - redis
    env_file:
      - ./.env-docker
    ports:
      - '7567:8000'

  celery:
    container_name: 'celery'
    build:
      context: ../../
    command: ['/app/docker/celery.sh', 'celery']
    depends_on:
      - redis
    env_file:
      - ./.env-docker

  flower:
    container_name: 'flower'
    build:
      context: ../../
    command: ['/app/docker/celery.sh', 'flower']
    depends_on:
      - redis
      - celery
    env_file:
      - ./.env-docker
    ports:
      - '8888:5555'

volumes:
  postgres_data:
  static:
  media:
